# Generated by Django 3.2.5 on 2022-02-13 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Main', '0002_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='usr',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('bazooka', models.CharField(max_length=250)),
            ],
        ),
    ]
