# Generated by Django 3.2.5 on 2022-02-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_dealer_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='material_weight',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='quantity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='age',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='capacity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='experience',
            field=models.CharField(max_length=100),
        ),
    ]
