# Generated by Django 3.2.5 on 2022-02-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20220213_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='routes',
            field=models.CharField(max_length=250),
        ),
    ]
