# Generated by Django 3.2.6 on 2022-02-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_driver_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='booking',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
